### ISSUE TITLE
[DEV] Create Template

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/intel-astro#1]
Create Default Layout Template
===
> Create the initial layout template for all pages to use.

**Tasks:**
- [x] Create main header component at the top displaying "Intel Astro"
- [x] Create sub-header component under main header displaying "Easily get up to date astronomical weather data"
- [x] Create main content area to display each page's content
