### ISSUE TITLE
[DESIGN] Design Astro Data Page

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/intel-astro#13]
Astro Data Page
===
> The page that displays the astro data to the user based on their previous selections.

**Tasks:**
- [x] Display each day within a separate card
- [x] Change sub-header to display:
- [x] User can click/tap on city or either date to change their respective values
```
City: [Selected City]
Dates: [Selected Start Date] - [Selected End Date]
```
