### ISSUE TITLE
[DEV] Create Header Component

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/intel-astro#2]
Header Component
===
> Create a separate component containing the header, allowing easy changes to be made in the future and to adhere to Atomic Design standards

**Tasks:**
- [x] Add "Intel Astro" text to component
- [x] Add styling
  - [x] Font size: 64
  - [x] Font weight: Lighter
  - [x] Font family: Roboto
