### ISSUE TITLE
[DEV] Create Sub-Header Component

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/intel-astro#3]
Sub-Header Component
===
> Create sub-header component to be placed into the default layout template

**Tasks:**
- [x] Add span element with "Easily get up to date astronomical weather data"
- [x] Add styling
  - [x] Text align: center
  - [x] Font size: 20
  - [x] Text color: rgba(0,0,0,.45);
