### ISSUE TITLE
[DEV] Create Autocomplete Component

### ISSUE THREAD

**Issue by RenegadeFox** [RenegadeFox/intel-astro#9]
Autocomplete Component
===
> An autocomplete text field to search cities and get their lat/long for the astro data.

**Tasks:**
- [x] Add API fetch capability
- [x] Add loading indicator SVG
- [x] Add U.S. state abbreviations
- [x] Clicking/Tapping results item should move to next page after selecting it
- [x] User can use arrow keys to navigate the results
- [x] User can hit `enter` to select results item

**Dependencies:**
[City Geo-Location Lookup API](https://rapidapi.com/dev132/api/city-geo-location-lookup)
[Axios](https://www.npmjs.com/package/axios)
